### PR TITLE
Now using spawn instead of exec to avoid maxBuffer errors.

### PR DESCRIPTION
**Pull request by aral**
In case you find it useful: I was getting maxBuffer exceeded errors when using electron-har programmatically – refactored to use spawn instead.

### CODE REVIEW

**Comment by bmcminn** [comment]
They main reason we used `cross-exec-file` was to mitigate node's indiscretion in resolving OS specific batch/shell scripts. Specifically with Windows https://github.com/shyiko/electron-har/issues/3

What OS are you running and have you tested in Windows?

**Comment by aral** [comment]
Ah, I see. I’m only testing on OS X at the moment.

Regarding the maxBuffer error, then, would it be worth testing setting that to a high enough buffer manually? (e.g., ala http://stackoverflow.com/a/23429654/253485) 

I had considered doing that first but [reading this](http://www.hacksparrow.com/difference-between-spawn-and-exec-of-node-js-child_process.html) made me reconsider:

> You can fix that problem by setting a bigger buffer size in the exec options. But you should not do it because exec is not meant for processes that return HUGE buffers to Node. You should use spawn for that. So what do you use exec for? Use it to run programs that return result statuses, instead of data.

Thoughts? :)

**Comment by bmcminn** [comment]
I'm curious what it is you're hitting that would cause a maxBuffer overload? Do you have an example URL you're capturing that consistently returns this error?

**Comment by aral** [comment]
I’m closing this pull request for the cross-platform issue as well as having majorly messed up the reduce function. Take a look at https://source.ind.ie/forks/electron-har/blob/master/src/index.js – where I’m now using cross-spawn-async, and let me know if you’d like me to cherry pick that and open a separate pull request (or feel free to just grab it) :)

**Pull request closed without merging**
